<template>
  <div class="loadingio-spinner-cube-6qthrzquas7">
    <div class="ldio-yj241jods7">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style type="text/css">
@keyframes ldio-yj241jods7 {
  0% {
    transform: scale(1.1500000000000001);
  }
  100% {
    transform: scale(1);
  }
}
.ldio-yj241jods7 div {
  position: absolute;
  width: 36px;
  height: 36px;
  top: 9.333333333333336px;
  left: 9.333333333333336px;
  background: #000000;
  animation: ldio-yj241jods7 1s cubic-bezier(0, 0.5, 0.5, 1) infinite;
  animation-delay: -0.3s;
}
.ldio-yj241jods7 div:nth-child(2) {
  top: 9.333333333333336px;
  left: 54.66666666666667px;
  background: #000000;
  animation-delay: -0.2s;
}
.ldio-yj241jods7 div:nth-child(3) {
  top: 54.66666666666667px;
  left: 9.333333333333336px;
  background: #000000;
  animation-delay: 0s;
}
.ldio-yj241jods7 div:nth-child(4) {
  top: 54.66666666666667px;
  left: 54.66666666666667px;
  background: #000000;
  animation-delay: -0.1s;
}
.loadingio-spinner-cube-6qthrzquas7 {
  width: 24px;
  height: 24px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-yj241jods7 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(0.24);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-yj241jods7 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
