name: CD
on:
  push:
    branches:
      - 'dev'

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
          STORAGE_SERVICE_ACCOUNT: ${{ secrets.STORAGE_SERVICE_ACCOUNT }}
        run: |
          docker build . --tag gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --build-arg FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }} --build-arg SERVICE_ACCOUNT=${{ secrets.SERVICE_ACCOUNT }} --build-arg STORAGE_SERVICE_ACCOUNT=${{ secrets.STORAGE_SERVICE_ACCOUNT }}

      - name: Authenticate into GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Configure Docker to use GCP
        run: 'gcloud auth configure-docker --quiet'

      - name: Push image to Google Cloud Container Registry
        run: docker push gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }}

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCLOUD_PROJECT }} --quiet --image gcr.io/${{ secrets.GCLOUD_PROJECT }}/${{ secrets.GCLOUD_APP_NAME }} --project ${{ secrets.GCLOUD_PROJECT }} --region europe-west1 --platform managed --allow-unauthenticated --max-instances 2
